.TH "include Directory Reference" 3 "Fri Mar 15 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCamera\&.hpp\fP"
.br
.RI "\fIHeader for the \fBCamera\fP class\&. \fP"
.ti -1c
.RI "file \fBCameras\&.hpp\fP"
.br
.RI "\fIHeader for the '\fBCameras\fP' class, a collection of \fBCamera\fP objects\&. \fP"
.ti -1c
.RI "file \fBEngine\&.hpp\fP"
.br
.RI "\fIHeader for the \fBEngine\fP class\&. \fP"
.ti -1c
.RI "file \fBglobals\&.h\fP"
.br
.RI "\fIUseful global constants, macros, debugging utilities and preprocessor settings\&. \fP"
.ti -1c
.RI "file \fBglut_callbacks\&.h\fP"
.br
.RI "\fI\fBglut_callbacks\&.h\fP provides function declarations for a set of functions commonly used across multiple binaries for keyboard, mouse and other GLUT callback functions\&. \fP"
.ti -1c
.RI "file \fBInitShader\&.hpp\fP"
.br
.RI "\fIProvides a wrapper utility for quickly linking against glsl programs\&. \fP"
.ti -1c
.RI "file \fBKinectInator\&.hpp\fP"
.br
.RI "\fITODO  FIXME\&. \fP"
.ti -1c
.RI "file \fBmat\&.hpp\fP"
.br
.RI "\fIHeaders for the mat2, mat3, and mat4 classes and related utilities\&. \fP"
.ti -1c
.RI "file \fBmodel\&.hpp\fP"
.br
.RI "\fIHeaders for Functions related to constructing simple geometry\&. \fP"
.ti -1c
.RI "file \fBmodelFunctions\&.hpp\fP"
.br
.ti -1c
.RI "file \fBObject\&.hpp\fP"
.br
.ti -1c
.RI "file \fBObjLoader\&.hpp\fP"
.br
.RI "\fIHeaders for functions for reading in geometry from \&.OBJ files\&. \fP"
.ti -1c
.RI "file \fBOpenGL\&.h\fP"
.br
.ti -1c
.RI "file \fBParticle\&.hpp\fP"
.br
.ti -1c
.RI "file \fBplatform\&.h\fP"
.br
.ti -1c
.RI "file \fBScene\&.hpp\fP"
.br
.ti -1c
.RI "file \fBScreen\&.hpp\fP"
.br
.ti -1c
.RI "file \fBSpelchkCamera\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTimer\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTransCache\&.hpp\fP"
.br
.ti -1c
.RI "file \fBTransformation\&.hpp\fP"
.br
.ti -1c
.RI "file \fBvec\&.hpp\fP"
.br
.ti -1c
.RI "file \fBWiiUtil\&.h\fP"
.br
.in -1c
