.TH "/home/nago/Dropbox/Spring 2013/Graphics II/S2/src/Binaries/ Directory Reference" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nago/Dropbox/Spring 2013/Graphics II/S2/src/Binaries/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBds\&.cpp\fP"
.br
.RI "\fIDual-shader demo\&. \fP"
.ti -1c
.RI "file \fBmelt\&.cpp\fP"
.br
.RI "\fIMelting Candle Demo\&. \fP"
.ti -1c
.RI "file \fBMONOLITH\&.cpp\fP"
.br
.RI "\fIThis is a monolith of every component\&. \fP"
.ti -1c
.RI "file \fBmorphlite\&.cpp\fP"
.br
.RI "\fIThis is a derivative of HSC's Fall 2012 project\&. \fP"
.ti -1c
.RI "file \fBpartTest\&.cpp\fP"
.br
.RI "\fIThis is a derivative of our main project file, fly\&.cpp\&. \fP"
.ti -1c
.RI "file \fBraytrace1\&.cpp\fP"
.br
.RI "\fIGeometric Raytracing Demo\&. \fP"
.ti -1c
.RI "file \fBterrain\&.cpp\fP"
.br
.RI "\fIThis is a trimmed version of our Fall 2012 project\&. \fP"
.ti -1c
.RI "file \fBzachMorphDemo\&.cpp\fP"
.br
.RI "\fIZach's Bottle Morphing Demo\&. \fP"
.in -1c
