.TH "/home/nago/Dropbox/Spring 2013/Graphics II/S2/src/Common/ Directory Reference" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/nago/Dropbox/Spring 2013/Graphics II/S2/src/Common/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBeric_rules\&.cpp\fP"
.br
.ti -1c
.RI "file \fBglut_callbacks\&.cpp\fP"
.br
.RI "\fIglut_callbacks provides function declarations for a set of functions commonly used across multiple binaries for keyboard, mouse and other GLUT callback functions\&. \fP"
.ti -1c
.RI "file \fBInitShader\&.cpp\fP"
.br
.RI "\fIProvides a wrapper utility for quickly linking against glsl programs\&. \fP"
.ti -1c
.RI "file \fBmodel\&.cpp\fP"
.br
.RI "\fIFunctions related to constructing simple geometry\&. \fP"
.ti -1c
.RI "file \fBmodelFunctions\&.cpp\fP"
.br
.RI "\fIFIXME: Documentation needed from Zach\&. \fP"
.ti -1c
.RI "file \fBObjLoader\&.cpp\fP"
.br
.RI "\fIImplementation for reading in geometry from \&.OBJ files\&. \fP"
.ti -1c
.RI "file \fBWiiUtil\&.cpp\fP"
.br
.RI "\fIWii Remote Utility Files\&. \fP"
.in -1c
