.TH "Angel::mat2" 3 "Fri Mar 15 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Angel::mat2 \- 
.PP
\fBmat2\fP - 2D square matrix\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mat\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmat2\fP (const GLfloat d=GLfloat(1\&.0))"
.br
.ti -1c
.RI "\fBmat2\fP (const \fBvec2\fP &a, const \fBvec2\fP &b)"
.br
.ti -1c
.RI "\fBmat2\fP (GLfloat m00, GLfloat m10, GLfloat m01, GLfloat m11)"
.br
.ti -1c
.RI "\fBmat2\fP (const \fBmat2\fP &m)"
.br
.ti -1c
.RI "\fBvec2\fP & \fBoperator[]\fP (int i)"
.br
.ti -1c
.RI "const \fBvec2\fP & \fBoperator[]\fP (int i) const "
.br
.ti -1c
.RI "\fBmat2\fP \fBoperator+\fP (const \fBmat2\fP &m) const "
.br
.ti -1c
.RI "\fBmat2\fP \fBoperator-\fP (const \fBmat2\fP &m) const "
.br
.ti -1c
.RI "\fBmat2\fP \fBoperator*\fP (const GLfloat s) const "
.br
.ti -1c
.RI "\fBmat2\fP \fBoperator/\fP (const GLfloat s) const "
.br
.ti -1c
.RI "\fBmat2\fP \fBoperator*\fP (const \fBmat2\fP &m) const "
.br
.ti -1c
.RI "\fBmat2\fP & \fBoperator+=\fP (const \fBmat2\fP &m)"
.br
.ti -1c
.RI "\fBmat2\fP & \fBoperator-=\fP (const \fBmat2\fP &m)"
.br
.ti -1c
.RI "\fBmat2\fP & \fBoperator*=\fP (const GLfloat s)"
.br
.ti -1c
.RI "\fBmat2\fP & \fBoperator*=\fP (const \fBmat2\fP &m)"
.br
.ti -1c
.RI "\fBmat2\fP & \fBoperator/=\fP (const GLfloat s)"
.br
.ti -1c
.RI "\fBvec2\fP \fBoperator*\fP (const \fBvec2\fP &v) const "
.br
.RI "\fIReturns the result of the operation M*v\&. \fP"
.ti -1c
.RI "\fBoperator const GLfloat *\fP () const "
.br
.ti -1c
.RI "\fBoperator GLfloat *\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBvec2\fP \fB_m\fP [2]"
.br
.RI "\fIThe data is stored as an array of two vectors\&. \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBmat2\fP \fBoperator*\fP (const GLfloat s, const \fBmat2\fP &m)"
.br
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &os, const \fBmat2\fP &m)"
.br
.ti -1c
.RI "std::istream & \fBoperator>>\fP (std::istream &is, \fBmat2\fP &m)"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBmat2\fP - 2D square matrix\&. 

\fBAuthor:\fP
.RS 4
Ed Angel Class for a 2x2 matrix\&. Modified from code available from Ed Angel's website, http://www.cs.unm.edu/~angel/BOOK/INTERACTIVE_COMPUTER_GRAPHICS/SIXTH_EDITION/ Published from his book, Interactive Computer Graphics A Top-Down Approach with OpenGL, Sixth Edition 
.RE
.PP

.PP
Definition at line 36 of file mat\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvec2\fP Angel::mat2::operator* (const \fBvec2\fP &v) const"

.PP
Returns the result of the operation M*v\&. Assumes v is a one column, two row matrix\&. 
.PP
Definition at line 154 of file mat\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBvec2\fP Angel::mat2::_m[2]\fC [private]\fP"

.PP
The data is stored as an array of two vectors\&. 
.PP
Definition at line 39 of file mat\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
