.TH "Camera.cpp" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Camera.cpp \- 
.PP
Implementation for the \fBCamera\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdexcept>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'mat\&.hpp'\fP
.br
\fC#include 'vec\&.hpp'\fP
.br
\fC#include 'Camera\&.hpp'\fP
.br
\fC#include 'globals\&.h'\fP
.br
\fC#include 'Timer\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBROTATE_OFFSET\fP(V)   (V * _ctm\&._orbit\&.matrix())"
.br
.RI "\fIROTATE_OFFSET is a macro which is used to normalize the six camera motion directions with respect to the current camera _rotation\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Implementation for the \fBCamera\fP class\&. 

\fBAuthor:\fP
.RS 4
John Huston 
.RE
.PP
\fBAuthors:\fP
.RS 4
John Huston, Nicholas StPierre, Chris Compton 
.RE
.PP
\fBDate:\fP
.RS 4
2012-12-20 
.RE
.PP

.PP
Definition in file \fBCamera\&.cpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ROTATE_OFFSET(V)   (V * _ctm\&._orbit\&.matrix())"

.PP
ROTATE_OFFSET is a macro which is used to normalize the six camera motion directions with respect to the current camera _rotation\&. It is used in heave(), sway() and surge()\&. 
.PP
\fBParameters:\fP
.RS 4
\fIV\fP a vec4 representing the movement _offset vector\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
A rotated vec4\&. 
.RE
.PP

.PP
Definition at line 184 of file Camera\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
