.TH "Cameras.hpp" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Cameras.hpp \- 
.PP
Header for the '\fBCameras\fP' class, a collection of \fBCamera\fP objects\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Camera\&.hpp'\fP
.br
\fC#include 'Scene\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCameras\fP"
.br
.RI "\fIThe \fBCameras\fP class represents a group of logical cameras for a model view\&. Each camera possesses its own current viewing angle, and an absolute position in space\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Header for the '\fBCameras\fP' class, a collection of \fBCamera\fP objects\&. 

\fBAuthor:\fP
.RS 4
John Huston 
.RE
.PP
\fBAuthors:\fP
.RS 4
John Huston, Nicholas StPierre, Chris Compton 
.RE
.PP
\fBDate:\fP
.RS 4
2012-12-04 
.RE
.PP

.PP
Definition in file \fBCameras\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
