.TH "mat.cpp" 3 "Fri Mar 15 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mat.cpp \- 
.PP
Implementation for the mat2, mat3, and mat4 classes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'platform\&.h'\fP
.br
\fC#include 'vec\&.hpp'\fP
.br
\fC#include 'mat\&.hpp'\fP
.br
\fC#include <cmath>\fP
.br
\fC#include 'globals\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "mat2 \fBAngel::operator*\fP (const GLfloat s, const mat2 &m)"
.br
.ti -1c
.RI "std::ostream & \fBAngel::operator<<\fP (std::ostream &os, const mat2 &m)"
.br
.ti -1c
.RI "std::istream & \fBAngel::operator>>\fP (std::istream &is, mat2 &m)"
.br
.ti -1c
.RI "mat2 \fBAngel::matrixCompMult\fP (const mat2 &A, const mat2 &B)"
.br
.ti -1c
.RI "mat2 \fBAngel::transpose\fP (const mat2 &A)"
.br
.ti -1c
.RI "mat3 \fBAngel::operator*\fP (const GLfloat s, const mat3 &m)"
.br
.ti -1c
.RI "std::ostream & \fBAngel::operator<<\fP (std::ostream &os, const mat3 &m)"
.br
.ti -1c
.RI "std::istream & \fBAngel::operator>>\fP (std::istream &is, mat3 &m)"
.br
.ti -1c
.RI "mat3 \fBAngel::matrixCompMult\fP (const mat3 &A, const mat3 &B)"
.br
.ti -1c
.RI "mat3 \fBAngel::transpose\fP (const mat3 &A)"
.br
.ti -1c
.RI "mat4 \fBAngel::operator*\fP (const GLfloat s, const mat4 &m)"
.br
.ti -1c
.RI "vec4 \fBAngel::operator*\fP (const vec4 &v, const mat4 &_m)"
.br
.ti -1c
.RI "std::ostream & \fBAngel::operator<<\fP (std::ostream &os, const mat4 &m)"
.br
.ti -1c
.RI "std::istream & \fBAngel::operator>>\fP (std::istream &is, mat4 &m)"
.br
.ti -1c
.RI "mat4 \fBAngel::matrixCompMult\fP (const mat4 &A, const mat4 &B)"
.br
.ti -1c
.RI "mat4 \fBAngel::transpose\fP (const mat4 &A)"
.br
.ti -1c
.RI "mat4 \fBAngel::RotateX\fP (const GLfloat theta)"
.br
.ti -1c
.RI "mat4 \fBAngel::RotateY\fP (const GLfloat theta)"
.br
.ti -1c
.RI "mat4 \fBAngel::RotateZ\fP (const GLfloat theta)"
.br
.ti -1c
.RI "mat4 \fBAngel::Translate\fP (const GLfloat x, const GLfloat y, const GLfloat z)"
.br
.ti -1c
.RI "mat4 \fBAngel::Translate\fP (const vec3 &v)"
.br
.ti -1c
.RI "mat4 \fBAngel::Translate\fP (const vec4 &v)"
.br
.ti -1c
.RI "mat4 \fBAngel::Scale\fP (const GLfloat x, const GLfloat y, const GLfloat z)"
.br
.ti -1c
.RI "mat4 \fBAngel::Scale\fP (const vec3 &v)"
.br
.ti -1c
.RI "mat4 \fBAngel::Ortho\fP (const GLfloat left, const GLfloat right, const GLfloat bottom, const GLfloat top, const GLfloat zNear, const GLfloat zFar)"
.br
.ti -1c
.RI "mat4 \fBAngel::Ortho2D\fP (const GLfloat left, const GLfloat right, const GLfloat bottom, const GLfloat top)"
.br
.ti -1c
.RI "mat4 \fBAngel::Frustum\fP (const GLfloat left, const GLfloat right, const GLfloat bottom, const GLfloat top, const GLfloat zNear, const GLfloat zFar)"
.br
.ti -1c
.RI "mat4 \fBAngel::Perspective\fP (const GLfloat fovy, const GLfloat aspect, const GLfloat zNear, const GLfloat zFar)"
.br
.ti -1c
.RI "mat4 \fBAngel::LookAt\fP (const vec4 &eye, const vec4 &at, const vec4 &up)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation for the mat2, mat3, and mat4 classes\&. 

\fBAuthor:\fP
.RS 4
Ed Angel 
.RE
.PP
\fBDate:\fP
.RS 4
2012-12-04
.RE
.PP
Modified heavily from code available from Ed Angel's website, http://www.cs.unm.edu/~angel/BOOK/INTERACTIVE_COMPUTER_GRAPHICS/SIXTH_EDITION/ Published from his book, Interactive Computer Graphics A Top-Down Approach with OpenGL, Sixth Edition Addison-Wesley 2012 
.PP
Definition in file \fBmat\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
