.TH "OpenGL.h" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OpenGL.h \- 
.PP
Core OpenGL includes needed for basic functionality\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <GL/glew\&.h>\fP
.br
\fC#include <GL/freeglut\&.h>\fP
.br
\fC#include <GL/freeglut_ext\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Core OpenGL includes needed for basic functionality\&. 

\fBDate:\fP
.RS 4
2013-03-15 
.RE
.PP
\fBAuthor:\fP
.RS 4
John Huston
.RE
.PP
Includes platform-dependent macros that need to be supported by the Makefile in order to function correctly on both Linux and OSX\&. 
.PP
Definition in file \fBOpenGL\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
