.TH "Particle" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Particle \- 
.PP
TODO: You know you've been bad\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Particle\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParticle\fP (\fBvec4\fP position, float scale, float lifeSpan)"
.br
.ti -1c
.RI "void \fBchangeVel\fP (\fBvec3\fP newVel)"
.br
.ti -1c
.RI "float \fBgetLifespan\fP (void)"
.br
.ti -1c
.RI "void \fBsetAlpha\fP (float newAlpha)"
.br
.ti -1c
.RI "void \fBsetColor\fP (\fBvec4\fP newColor)"
.br
.ti -1c
.RI "void \fBsetLifespan\fP (float newLifespan)"
.br
.ti -1c
.RI "void \fBsetPos\fP (\fBvec4\fP newPos)"
.br
.ti -1c
.RI "void \fBsetScale\fP (\fBvec3\fP newScale)"
.br
.ti -1c
.RI "void \fBsetSpin\fP (float newSpin)"
.br
.ti -1c
.RI "void \fBsetVel\fP (\fBvec3\fP newVel)"
.br
.ti -1c
.RI "void \fBsetTexFile\fP (string newFilename)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBvec4\fP \fBmPos\fP"
.br
.ti -1c
.RI "\fBvec3\fP \fBmScale\fP"
.br
.ti -1c
.RI "\fBvec3\fP \fBmVel\fP"
.br
.ti -1c
.RI "\fBvec4\fP \fBcolor\fP"
.br
.ti -1c
.RI "float \fBlifespan\fP"
.br
.ti -1c
.RI "string \fBtexFilename\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TODO: You know you've been bad\&. 

\fBAuthor:\fP
.RS 4
Nick Ver Voort, nicholas_vervoort@student.uml.edu 
.RE
.PP
\fBSince:\fP
.RS 4
23 Feb 2013 
.RE
.PP
\fBAuthors:\fP
.RS 4
Nick Ver Voort, Chris Compton nicholas_vervoort@student.uml.edu, christopher_compton@student.uml.edu 
.RE
.PP

.PP
Definition at line 31 of file Particle\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
