.TH "Particle.hpp" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Particle.hpp \- 
.PP
FIXME: Needs documentation from NVV/CC\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'mat\&.hpp'\fP
.br
\fC#include 'vec\&.hpp'\fP
.br
\fC#include 'Object\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParticle\fP"
.br
.RI "\fITODO: You know you've been bad\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
FIXME: Needs documentation from NVV/CC\&. 

\fBAuthor:\fP
.RS 4
FIXME 
.RE
.PP
\fBAuthors:\fP
.RS 4
FIXME 
.RE
.PP
\fBDate:\fP
.RS 4
2013-03-15 
.RE
.PP

.PP
Definition in file \fBParticle\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
