.TH "Particle.cpp" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Particle.cpp \- 
.PP
FIXME: Needs documentation from NVV/CC\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'globals\&.h'\fP
.br
\fC#include 'mat\&.hpp'\fP
.br
\fC#include 'model\&.hpp'\fP
.br
\fC#include 'Object\&.hpp'\fP
.br
\fC#include 'Particle\&.hpp'\fP
.br
\fC#include 'platform\&.h'\fP
.br
\fC#include 'Timer\&.hpp'\fP
.br
\fC#include 'vec\&.hpp'\fP
.br

.SH "Detailed Description"
.PP 
FIXME: Needs documentation from NVV/CC\&. 

\fBAuthor:\fP
.RS 4
FIXME 
.RE
.PP
\fBAuthors:\fP
.RS 4
FIXME 
.RE
.PP
\fBDate:\fP
.RS 4
2013-03-15 
.RE
.PP

.PP
Definition in file \fBParticle\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
