.TH "RotMat" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RotMat \- 
.PP
Rotations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Transformation\&.hpp>\fP
.PP
Inherits \fBTransformation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBRotMat\fP & \fBreset\fP (const \fBAngel::mat4\fP &NewState)"
.br
.ti -1c
.RI "const \fBRotMat\fP & \fBrotateX\fP (const GLfloat theta, bool postmult=true)"
.br
.ti -1c
.RI "const \fBRotMat\fP & \fBrotateY\fP (const GLfloat theta, bool postmult=true)"
.br
.ti -1c
.RI "const \fBRotMat\fP & \fBrotateZ\fP (const GLfloat theta, bool postmult=true)"
.br
.ti -1c
.RI "const \fBRotMat\fP & \fBadjust\fP (const \fBAngel::mat4\fP &Adjustment, bool postmult=true)"
.br
.ti -1c
.RI "const \fBAngel::mat4\fP & \fBmatrix\fP (void) const "
.br
.ti -1c
.RI "\fBAngel::mat4\fP \fBoperator*\fP (const \fBAngel::mat4\fP &rhs) const "
.br
.ti -1c
.RI "\fBAngel::mat4\fP \fBoperator*\fP (const \fBTransformation\fP &rhs) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBAngel::mat4\fP \fBmat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Rotations\&. 
.PP
Definition at line 40 of file Transformation\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
