.TH "ScaleMat" 3 "Fri Mar 15 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ScaleMat \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTransformation\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const \fBScaleMat\fP & \fBSet\fP (const float x, const float y, const float z)"
.br
.ti -1c
.RI "const \fBScaleMat\fP & \fBSet\fP (const float pct)"
.br
.ti -1c
.RI "const \fBScaleMat\fP & \fBAdjust\fP (const float x, const float y, const float z)"
.br
.ti -1c
.RI "const \fBScaleMat\fP & \fBAdjust\fP (const float pct)"
.br
.ti -1c
.RI "const \fBAngel::mat4\fP & \fBMatrix\fP (void) const "
.br
.ti -1c
.RI "\fBAngel::mat4\fP \fBoperator*\fP (const \fBAngel::mat4\fP &rhs) const "
.br
.ti -1c
.RI "\fBAngel::mat4\fP \fBoperator*\fP (const \fBTransformation\fP &rhs) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBAngel::mat4\fP \fBmat\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 63 of file Transformation\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
