.TH "Screen" 3 "Fri Mar 15 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Screen \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreen\fP (int x=0, int y=0)"
.br
.ti -1c
.RI "\fBScreen\fP (const \fBvec2\fP &newSize)"
.br
.ti -1c
.RI "void \fBSize\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBSize\fP (const \fBvec2\fP &newSize)"
.br
.ti -1c
.RI "const \fBvec2\fP & \fBSize\fP (void)"
.br
.ti -1c
.RI "int \fBWidth\fP (void)"
.br
.ti -1c
.RI "int \fBHeight\fP (void)"
.br
.ti -1c
.RI "const \fBvec2\fP & \fBCenter\fP (void)"
.br
.ti -1c
.RI "int \fBMidpointX\fP (void)"
.br
.ti -1c
.RI "int \fBMidpointY\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCameras\fP \fB_camList\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBvec2\fP \fB_size\fP"
.br
.ti -1c
.RI "\fBvec2\fP \fB_center\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file Screen\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
