.TH "Screen" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Screen \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBScreen\fP (int x=0, int y=0)"
.br
.ti -1c
.RI "\fBScreen\fP (const \fBvec2\fP &newSize)"
.br
.ti -1c
.RI "void \fBsize\fP (int x, int y)"
.br
.ti -1c
.RI "void \fBsize\fP (const \fBvec2\fP &newSize)"
.br
.ti -1c
.RI "const \fBvec2\fP & \fBsize\fP (void)"
.br
.ti -1c
.RI "int \fBwidth\fP (void)"
.br
.ti -1c
.RI "int \fBheight\fP (void)"
.br
.ti -1c
.RI "const \fBvec2\fP & \fBcenter\fP (void)"
.br
.ti -1c
.RI "int \fBmidpointX\fP (void)"
.br
.ti -1c
.RI "int \fBmidpointY\fP (void)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCameras\fP \fB_camList\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBvec2\fP \fB_size\fP"
.br
.ti -1c
.RI "\fBvec2\fP \fB_center\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file Screen\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
