.TH "SpelchkCamera" 3 "Fri Mar 29 2013" "Version 31337" "HyperGrafx" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpelchkCamera \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpelchkCamera\fP (\fBvec4\fP initialTranslationVector)"
.br
.ti -1c
.RI "\fBmat4\fP \fBgetProjectionMatrix\fP ()"
.br
.ti -1c
.RI "\fBmat4\fP \fBgetModelViewMatrix\fP ()"
.br
.ti -1c
.RI "\fBvec4\fP \fBgetTranslationVector\fP ()"
.br
.ti -1c
.RI "void \fBmoveCamera\fP (float xDepth, float yDepth, float zDepth)"
.br
.ti -1c
.RI "void \fBrotateCamera\fP (float xAngle, float yAngle, float zAngle)"
.br
.ti -1c
.RI "void \fBsetScreenSize\fP (int width, int height)"
.br
.ti -1c
.RI "void \fBsetProjection\fP (int projectionType)"
.br
.ti -1c
.RI "void \fBreset\fP ()"
.br
.ti -1c
.RI "void \fBsetLightMovementRef\fP (GLuint ref)"
.br
.ti -1c
.RI "void \fBsetLightMovementTime\fP (float elapsed)"
.br
.ti -1c
.RI "void \fBgetReadyForZero\fP (int usernum)"
.br
.ti -1c
.RI "void \fBheadMovement\fP (int usernum, double x, double y, double z)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBcalculateTranslationVector\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fB_projectionType\fP"
.br
.ti -1c
.RI "GLfloat \fB_fovy\fP"
.br
.ti -1c
.RI "GLfloat \fB_aspect\fP"
.br
.ti -1c
.RI "GLfloat \fB_left\fP"
.br
.ti -1c
.RI "GLfloat \fB_right\fP"
.br
.ti -1c
.RI "GLfloat \fB_bottom\fP"
.br
.ti -1c
.RI "GLfloat \fB_top\fP"
.br
.ti -1c
.RI "GLfloat \fB_zNear\fP"
.br
.ti -1c
.RI "GLfloat \fB_zFar\fP"
.br
.ti -1c
.RI "GLuint \fB_timeRef\fP"
.br
.ti -1c
.RI "int \fB_screenWidth\fP"
.br
.ti -1c
.RI "int \fB_screenHeight\fP"
.br
.ti -1c
.RI "GLfloat \fB_xDepth\fP"
.br
.ti -1c
.RI "GLfloat \fB_yDepth\fP"
.br
.ti -1c
.RI "GLfloat \fB_zDepth\fP"
.br
.ti -1c
.RI "GLfloat \fB_xAngle\fP"
.br
.ti -1c
.RI "GLfloat \fB_yAngle\fP"
.br
.ti -1c
.RI "GLfloat \fB_zAngle\fP"
.br
.ti -1c
.RI "GLfloat \fB_xHead\fP"
.br
.ti -1c
.RI "GLfloat \fB_yHead\fP"
.br
.ti -1c
.RI "GLfloat \fB_zHead\fP"
.br
.ti -1c
.RI "float \fB_xHeadStart\fP"
.br
.ti -1c
.RI "float \fB_yHeadStart\fP"
.br
.ti -1c
.RI "float \fB_zHeadStart\fP"
.br
.ti -1c
.RI "GLfloat \fB_xHeadAngle\fP"
.br
.ti -1c
.RI "GLfloat \fB_yHeadAngle\fP"
.br
.ti -1c
.RI "GLfloat \fB_zHeadAngle\fP"
.br
.ti -1c
.RI "\fBvec4\fP \fB_initialTranslationVector\fP"
.br
.ti -1c
.RI "\fBvec4\fP \fB_translationVector\fP"
.br
.ti -1c
.RI "\fBvec4\fP \fB_oldTranslationVector\fP"
.br
.ti -1c
.RI "\fBmat4\fP \fB_modelViewMatrix\fP"
.br
.ti -1c
.RI "int \fB_inboundHeadData\fP"
.br
.ti -1c
.RI "\fBvec4\fP \fB_initialHeadPosition\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file SpelchkCamera\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for HyperGrafx from the source code\&.
